### ISSUE TITLE
Create data model

### ISSUE THREAD

**Issue by ahackit** [ahackit/OnlyGoodRecipes#12]
USER_L
user_id
username
password
email

RECIPE_L
recipe_id
recipe_name
recipe_genre_id
recipe_diff_id
recipe_time

RECIPE_GENRE_L
recipe_genre_id
recip_genre_dsc

RECIPE_DIFF_L
recipe_diff_id
recipe_diff_dsc

STEPS_L
recipe_id
step_dsc
step_notes
step_order

INGREDIENTS_L
recipe_id
ing_id
ing_dsc
ing_amt
grocery_id

GROCERY_L
grocery_id
grocery_type

**Comment by dsamsondeen** [comment]
hi. what does dsc mean
